/* 
 * BookStore.CartApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CartHeaderDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartHeaderDtoTests
    {
        // TODO uncomment below to declare an instance variable for CartHeaderDto
        //private CartHeaderDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartHeaderDto
            //instance = new CartHeaderDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartHeaderDto
        /// </summary>
        [Test]
        public void CartHeaderDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartHeaderDto
            //Assert.IsInstanceOfType<CartHeaderDto> (instance, "variable 'instance' is a CartHeaderDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'CouponCode'
        /// </summary>
        [Test]
        public void CouponCodeTest()
        {
            // TODO unit test for the property 'CouponCode'
        }

    }

}
