/* 
 * BookStore.CartApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CartDto
    /// </summary>
    [DataContract]
        public partial class CartDto :  IEquatable<CartDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartDto" /> class.
        /// </summary>
        /// <param name="cartHeader">cartHeader.</param>
        /// <param name="cartDetails">cartDetails.</param>
        public CartDto(CartHeader cartHeader = default(CartHeader), List<CartDetails> cartDetails = default(List<CartDetails>))
        {
            this.CartHeader = cartHeader;
            this.CartDetails = cartDetails;
        }
        
        /// <summary>
        /// Gets or Sets CartHeader
        /// </summary>
        [DataMember(Name="cartHeader", EmitDefaultValue=false)]
        public CartHeader CartHeader { get; set; }

        /// <summary>
        /// Gets or Sets CartDetails
        /// </summary>
        [DataMember(Name="cartDetails", EmitDefaultValue=false)]
        public List<CartDetails> CartDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartDto {\n");
            sb.Append("  CartHeader: ").Append(CartHeader).Append("\n");
            sb.Append("  CartDetails: ").Append(CartDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CartDto);
        }

        /// <summary>
        /// Returns true if CartDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CartDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CartHeader == input.CartHeader ||
                    (this.CartHeader != null &&
                    this.CartHeader.Equals(input.CartHeader))
                ) && 
                (
                    this.CartDetails == input.CartDetails ||
                    this.CartDetails != null &&
                    input.CartDetails != null &&
                    this.CartDetails.SequenceEqual(input.CartDetails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CartHeader != null)
                    hashCode = hashCode * 59 + this.CartHeader.GetHashCode();
                if (this.CartDetails != null)
                    hashCode = hashCode * 59 + this.CartDetails.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
