// <auto-generated />
using System;
using CodeGround.Modeling;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeGround.Modeling.Migrations
{
    [DbContext(typeof(InvoiceContext))]
    partial class InvoiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("GodeGround.Modeling.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("GodeGround.Modeling.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rounding")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("GodeGround.Modeling.Models.RecurringInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("RecurringInvoices");
                });

            modelBuilder.Entity("GodeGround.Modeling.Models.Invoice", b =>
                {
                    b.HasOne("GodeGround.Modeling.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GodeGround.Modeling.Models.RecurringInvoice", b =>
                {
                    b.HasOne("GodeGround.Modeling.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GodeGround.Modeling.Models.RecurringInvoiceScheduling", "RecurringInvoiceScheduling", b1 =>
                        {
                            b1.Property<Guid>("RecurringInvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CreateDaysBeforePublish")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("NumberOfOccurrances")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Occurrance")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("RecurringInvoiceId");

                            b1.ToTable("RecurringInvoices");

                            b1.WithOwner()
                                .HasForeignKey("RecurringInvoiceId");
                        });

                    b.Navigation("Company");

                    b.Navigation("RecurringInvoiceScheduling");
                });
#pragma warning restore 612, 618
        }
    }
}
