/* 
 * BookStore.CartApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CartApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CartApiTests
    {
        private CartApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CartApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CartApi
            //Assert.IsInstanceOfType(typeof(CartApi), instance, "instance is a CartApi");
        }

        /// <summary>
        /// Test AddCart
        /// </summary>
        [Test]
        public void AddCartTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartDto body = null;
            //instance.AddCart(body);
            
        }
        /// <summary>
        /// Test DeleteCart
        /// </summary>
        [Test]
        public void DeleteCartTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? cartHeaderId = null;
            //instance.DeleteCart(cartHeaderId);
            
        }
        /// <summary>
        /// Test GetCart
        /// </summary>
        [Test]
        public void GetCartTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? userId = null;
            //instance.GetCart(userId);
            
        }
        /// <summary>
        /// Test UpdateCart
        /// </summary>
        [Test]
        public void UpdateCartTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartDto body = null;
            //Guid? cartHeaderId = null;
            //instance.UpdateCart(body, cartHeaderId);
            
        }
    }

}
